# One colour theme for the whole environment, e.g.
#   devEnv.theme.name = "catppuccin-mocha";
#   devEnv.theme.background = "#211535";   # optional
#
# The palettes are in themes/palettes.json (generated by themes/update.sh).
# What follows the theme, and how:
#
# - The outer terminal (Ghostty over SSH, Windows Terminal on WSL): its 16 ANSI
#   colours, foreground, background and cursor are written with OSC escape
#   sequences (OSC 4, 10/11/12). On the Mac VMs, `herdr-attach` (the Makefile's
#   SSH_CMD) writes them before attaching and resets them on detach. On WSL the
#   first interactive zsh, outside herdr, writes them.
# - herdr: with `[theme] name = "terminal"` its sidebar and panes show the
#   terminal's background, and the rest uses ANSI colours. herdr's other themes
#   paint only text, highlights and the tab bar, never the pane background.
# - Panes inside herdr ($HERDR_PANE_ID set) write nothing: herdr emulates each
#   pane, so a colour set there would pin that pane instead of reaching the
#   terminal. That's why this isn't done from every shell.
# - Everything that prints ANSI colour indices (prompt, ls, fzf, git, zsh
#   syntax highlighting) follows the terminal.
# - nvim: ~/.config/dev-env/theme.json names the matching colorscheme, applied
#   by the dev-env-theme plugin (themes/nvim, linked to
#   ~/.local/share/dev-env/theme.nvim), with a transparent background.
# - pi: a `dev-env` theme at ~/.pi/agent/themes/dev-env.json, built from the palette.
#
# A new palette reaches the terminal on the next attach, and nvim on restart.
{ config, lib, pkgs, ... }:

let
  cfg = config.devEnv.theme;

  palettes = lib.importJSON ../../themes/palettes.json;
  families = lib.importJSON ../../themes/nvim/families.json;

  selected = palettes.${cfg.name};
  palette = selected // lib.optionalAttrs (cfg.background != null) {
    background = lib.toLower cfg.background;
  };

  # Real escape characters, so the sequences can sit in single quotes in shell.
  esc = builtins.fromJSON ''"\u001b"'';
  st = "${esc}\\";
  osc = body: "${esc}]${body}${st}";

  # One write for the whole palette, so the terminal repaints once.
  setSequences =
    lib.concatStrings (lib.imap0 (i: colour: osc "4;${toString i};${colour}") palette.ansi)
    + osc "10;${palette.foreground}"
    + osc "11;${palette.background}"
    + osc "12;${palette.cursor}";
  # Back to the terminal's own colours: palette, foreground, background, cursor.
  resetSequences = osc "104" + osc "110" + osc "111" + osc "112";

  # Colour arithmetic for the pi theme, which needs a few in-between shades.
  channels = c: map (i: lib.fromHexString (builtins.substring i 2 c)) [ 1 3 5 ];
  hex2 = n:
    let h = lib.toLower (lib.toHexString n);
    in if builtins.stringLength h == 1 then "0${h}" else h;
  # `pct` percent of b into a.
  mix = a: b: pct: "#" + lib.concatStrings (lib.zipListsWith
    (x: y: hex2 ((x * (100 - pct) + y * pct + 50) / 100))
    (channels a) (channels b));

  ansi = i: builtins.elemAt palette.ansi i;
  bg = palette.background;
  fg = palette.foreground;

  piTheme = {
    "$schema" = "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json";
    name = "dev-env";
    vars = {
      text = fg;
      gray = mix fg bg 45;
      dimGray = mix fg bg 60;
      darkGray = mix fg bg 75;
      red = ansi 1;
      green = ansi 2;
      yellow = ansi 3;
      blue = ansi 4;
      magenta = ansi 5;
      cyan = ansi 6;
      selectedBg = mix bg fg 15;
      userMsgBg = mix bg fg 8;
      toolPendingBg = mix bg fg 5;
      toolSuccessBg = mix bg (ansi 2) 10;
      toolErrorBg = mix bg (ansi 1) 12;
      customMsgBg = mix bg (ansi 5) 10;
    };
    colors = {
      accent = "blue";
      border = "blue";
      borderAccent = "cyan";
      borderMuted = "darkGray";
      success = "green";
      error = "red";
      warning = "yellow";
      muted = "gray";
      dim = "dimGray";
      text = "text";
      thinkingText = "gray";

      selectedBg = "selectedBg";
      scrollbarTrack = "darkGray";
      scrollbarThumb = "gray";
      searchMatchBg = "selectedBg";
      searchMatchText = "text";
      userMessageBg = "userMsgBg";
      userMessageText = "text";
      customMessageBg = "customMsgBg";
      customMessageText = "text";
      customMessageLabel = "magenta";
      toolPendingBg = "toolPendingBg";
      toolSuccessBg = "toolSuccessBg";
      toolErrorBg = "toolErrorBg";
      toolTitle = "text";
      toolOutput = "gray";

      mdHeading = "yellow";
      mdLink = "blue";
      mdLinkUrl = "dimGray";
      mdCode = "cyan";
      mdCodeBlock = "green";
      mdCodeBlockBorder = "gray";
      mdQuote = "gray";
      mdQuoteBorder = "gray";
      mdHr = "gray";
      mdListBullet = "blue";

      toolDiffAdded = "green";
      toolDiffRemoved = "red";
      toolDiffContext = "gray";

      syntaxComment = "dimGray";
      syntaxKeyword = "magenta";
      syntaxFunction = "blue";
      syntaxVariable = "text";
      syntaxString = "green";
      syntaxNumber = "yellow";
      syntaxType = "cyan";
      syntaxOperator = "text";
      syntaxPunctuation = "gray";

      thinkingOff = "darkGray";
      thinkingMinimal = "dimGray";
      thinkingLow = "blue";
      thinkingMedium = "cyan";
      thinkingHigh = "magenta";
      thinkingXhigh = "red";
      thinkingMax = "red";

      bashMode = "green";
    };
    export = {
      pageBg = bg;
      cardBg = mix bg fg 5;
      infoBg = mix bg (ansi 3) 12;
    };
  };

  # Writes the palette to the terminal, runs herdr, and puts the terminal's own
  # colours back on detach. herdr reads the terminal's colours when it attaches.
  herdrAttach = pkgs.writeShellScriptBin "herdr-attach" (
    if cfg.name == null then ''
      exec herdr "$@"
    '' else ''
      # devEnv.theme: ${cfg.name}
      if [ -t 1 ] && [ -z "''${HERDR_PANE_ID:-}" ]; then
        printf '%s' '${setSequences}'
        reset_colours() { printf '%s' '${resetSequences}'; }
        trap reset_colours EXIT
      fi
      herdr "$@"
    ''
  );
in
{
  imports = [
    (lib.mkRenamedOptionModule [ "devEnv" "terminalPalette" ] [ "devEnv" "theme" "name" ])
  ];

  options.devEnv.theme = {
    name = lib.mkOption {
      type = lib.types.nullOr (lib.types.enum (lib.attrNames palettes));
      default = null;
      example = "catppuccin-mocha";
      description = ''
        Colour theme for the terminal, herdr, nvim and pi (themes/palettes.json
        lists them), or null to leave every tool's own colours alone.
      '';
    };
    background = lib.mkOption {
      type = lib.types.nullOr (lib.types.strMatching "#[0-9a-fA-F]{6}");
      default = null;
      example = "#211535";
      description = ''
        Replaces the theme's background colour, e.g. to tell two machines
        apart. nvim is transparent, so it follows.
      '';
    };
  };

  config = lib.mkMerge [
    {
      home.packages = [ herdrAttach ];

      # The nvim plugin; the private nvim config loads spec.lua from here.
      xdg.dataFile."dev-env/theme.nvim".source = ../../themes/nvim;

      assertions = [{
        assertion = lib.all (p: families ? ${p.nvim.family}) (lib.attrValues palettes);
        message = "themes/palettes.json uses an nvim family that themes/nvim/families.json lacks.";
      }];
    }

    (lib.mkIf (cfg.name != null) {
      # Order 500 so the colours are in place before anything prints: the
      # prompt, Oh My Zsh's output, and the "plugin not found" notice come later.
      programs.zsh.initContent = lib.mkOrder 500 ''
        # Terminal colours (devEnv.theme: ${cfg.name}). Only for a real
        # interactive terminal: escape sequences in a pipe corrupt the reader,
        # and the Linux console and dumb terminals don't take OSC. Not inside
        # herdr, where they'd pin the pane instead of reaching the terminal.
        if [[ -o interactive && -t 1 && $TERM != (dumb|linux) && -z $HERDR_PANE_ID ]]; then
          print -rn -- '${setSequences}'
        fi
      '';

      xdg.configFile."dev-env/theme.json".text = builtins.toJSON {
        inherit (cfg) name;
        inherit (palette) appearance background foreground cursor ansi nvim;
      };

      home.file.".pi/agent/themes/dev-env.json".text = builtins.toJSON piTheme;
    })
  ];
}
